sudo: false
language: java
jdk: oraclejdk8

cache:
  bundler: true
  directories:
  - "$HOME/.m2/repository"


#before_install: Not needed anymore cause theme and template are deployed to central snapshots on each commit
#- git clone https://github.com/adminfaces/admin-theme.git ~/builds/admin-theme
#- cd ~/builds/admin-theme && mvn install
#- git clone https://github.com/adminfaces/admin-template.git ~/builds/admin-template
#- cd ~/builds/admin-template && mvn install


before_script:
  - rm -r $HOME/.m2/repository/com/github/adminfaces/

script:
- mvn -U clean package -Pwildfly8-managed -Dtravisci -Dbrowser=phantomjs
- mvn -U clean package -Pwildfly8-managed -Dtravisci -Dbrowser=phantomjs
- mvn test -Pglassfish-managed -Dtravisci -Dbrowser=phantomjs
- mvn test -Ptomee7-remote -Dtravisci -Dbrowser=phantomjs
- mvn test -Ptomee1.7-remote -Dtravisci -Dbrowser=phantomjs


deploy:
  provider: openshift
  user: rmpestano@gmail.com
  skip_cleanup: true
  password:
    secure: cymNmxSbhmPQYCqMyjMNlxU5HqgbsfLLiufGU9hESnNrC26d8OXm3uzGf5NxwjPi+WQT5NYP0fyPwpkl5S1P1bmxx2pwYMsHiK1DzzvN3VBpGq24K7KxYvB7XDd/GRWXY/9eT5I3n+wYrsSEeDQ66f0PtFaExYUsha+rIym93cShp0tVYPKHJ8G+D4Md8D2xdsArtoESKMupnFfKUADxQ0P12XStEth5wqxDKKq3xRQorYdNroeZQ8iWBEaRexXfO8HWmVOPdlPWMniu/LESjVXKSRi8ZetQJ2lTTFnRdzld1pQ03efMa7jd6gwOaxMPVKV8VHtVW6qT1xHcQRtU/v2x4DtsfPUZup5tEdRvlLyeicGLC9HJfOnlLnv+j21N5hotbSlbHop/j/gtaSnHfT8t1aMtubNtOs0oy5VpsaRgEyMFiq16/mHdal5qT96tfY4nrndnm3TNj5VmUvh8WvguJoD+akzwdiBV7qY9Tvlb7l+byCt7KgSDeUjhISSK/wVzKg5y5D1POX6OHABKSdoWZ9hDsPlwFTbyBGWgdsOoKdxDa15JlmseQd5J3zF1AwQdOxYioWNYrCPnW54j0JEJxe9zBfG4mJ8GgKYMZIkkE4HW6alYdO2qTWoxzL5qftEhbHTQUMIzXT7DFZh2mIlsrbEClnSW7ckTpmbnZCA=
  app: adminfaces
  domain: rpestano
  on:
    repo: adminfaces/admin-showcase
